#!/usr/bin/env bash
# Nginx server to have a custom 404 page
sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
