#!/usr/bin/env bash
# Install HAProxy

sudo apt-get update
sudo apt-get install -y haproxy

echo 'ENABLED=1' >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 359213-web-01 54.157.145.222:80 check
    server 359213-web-02 100.26.227.184:80 check
CONFIG

cat << 'EOF' | sudo tee /etc/init.d/haproxy
#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAProxy balancer
# Description:       Makes sure that HAproxy can be managed via an init script
### END INIT INFO

haproxy -f /etc/haproxy/haproxy.cfg -D -p /var/run/haproxy.pid
EOF

sudo chmod +x /etc/init.d/haproxy

sudo service haproxy start

sudo update-rc.d haproxy defaults