#!/usr/bin/env bash
# Install HAProxy

sudo apt-get update
sudo apt-get install -y haproxy

cat << 'EOF' | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.157.145.222:80 check
    server web-02 100.26.227.184:80 check
EOF


cat << 'EOF' | sudo tee /etc/init.d/haproxy

haproxy -f /etc/haproxy/haproxy.cfg -D -p /var/run/haproxy.pid
EOF

sudo chmod +x /etc/init.d/haproxy

sudo service haproxy start

sudo update-rc.d haproxy defaults