#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.
#Requirements:
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5

for no in {1..100}
do
  if (( no % 3 == 0 && no % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( no % 3 == 0 ))
  then
    echo "Fizz"
  elif (( no % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$no"
  fi
done