#!/usr/bin/env bash
# fix docker issue 
docker stop vigilant_tesla

docker exec -it vigilant_tesla apt-get update && apt-get install -y apache2

docker exec -it vigilant_tesla systemctl enable apache2

docker exec -it vigilant_tesla systemctl start apache2

echo '<!DOCTYPE html><html><head><title>Holberton</title></head><body><h1>Hello Holberton</h1></body></html>' | docker exec -it vigilant_tesla tee /var/www/html/index.html

docker exec -it vigilant_tesla systemctl restart apache2
