#!/usr/bin/env bash
# fix docker issue 

cat <<EOF > index.html
<!DOCTYPE html>
<html>
<head>
  <title>Hello Holberton</title>
</head>
<body>
  <h1>Hello Holberton</h1>
</body>
</html>
EOF

COPY index.html /usr/local/apache2/htdocs/

docker exec -it vigilant_tesla systemctl restart apache2
